repos:
  - repo: local
    hooks:
      - id: run-make-fmt
        name: Formatter
        entry: /usr/bin/make
        language: script
        args: ["fmt"]

      - id: run-make-lint
        name: Linter
        entry: /usr/bin/make
        language: script
        args: ["lint"]

      - id: run-make-db
        name: DB Validation
        entry: /usr/bin/make
        language: script
        args: ["db"]

      - id: run-make-test
        name: Tests
        entry: /usr/bin/make
        language: script
        args: ["test"]
        require_serial: true
